### ISSUE TITLE
Fix pytest warnings

### ISSUE THREAD

**Issue by cjfullerton** [hpcflow/hpcflow-new#398]
There are a lot (~700).

**Comment by aplowman** [comment]
I've fixed most of the warnings in ac1c515469f4c46eb959e4316b9cdaf6212afdbe

Most of the remaining warnings are from Numpy via Zarr, and I believe originate from this bug in Numpy: https://github.com/numpy/numpy/issues/13548, whose fix has not yet made it into a release, I think. (We are using a `np.datetime64()` object as a fill value in a Zarr array, and Zarr compares the fill value to zero when constructing the array.)

The invalid escape sequence `DeprecationWarning` (https://github.com/hpcflow/hpcflow-new/issues/382) that only shows up on CI and not locally still eludes me!

**Comment by aplowman** [comment]
Invalid escape sequence warning fixed in f741f74f6e8ec0a31ac6725ca0285b54b2e8327a. I was misled by the warning location, which is shown at the start of a triple-quoted string, rather than within the string somewhere. (Although I still don't know why the warnings weren't issued on my computer.)

Using numpy-1.25.0rc1 (just released) the Numpy warnings disappear. However, this version of Numpy requires Python 3.9 as a minimum, which means we can't upgrade to it when it is stably released until we bump our minimum version to 3.9 in 2024. So, I have wrapped the offending code in a `with warnings.catch_warnings():` for now in 46b6a853c1bf043aad59a928e6ed7ee4905e2ce8.

**Comment by aplowman** [comment]
All fixed in https://github.com/hpcflow/hpcflow-new/pull/405.
